[package]
name = "rust-doh-nut"
version = "0.1.0"
authors = ["Aron Tsang <arontsang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arr_macro = "0.1.3"
async-trait = "0.1.21"
bytes = "0.5.3"
reqwest = { version = "0.10.0", features = ["native-tls-vendored"] }
tokio = { version = "0.2.6", features = ["full"]}



[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1
