[package]
name = "rust-doh-nut"
version = "0.1.0"
authors = ["Aron Tsang <arontsang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arr_macro = "0.1.3"
async-trait = "0.1.21"
bytes = "0.5.3"
futures = "0.3.1"
futures-timer = "2.0.2"
reqwest = { version = "0.10.0", features = ["native-tls", "stream"] }
tokio = { version = "0.2.6", features = ["macros", "rt-core", "rt-util", "sync", "udp", "tcp"]}

[dependencies.async-std]
version = "1.0.0"
default-features = false
features = ["std"]