[package]
name = "rust-doh-nut"
version = "0.1.0"
authors = ["Aron Tsang <arontsang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arr_macro = "0.1"
async-trait = "0.1"
bytes = "0.5"
reqwest = { version = "0.10", features = ["native-tls-vendored"] }
rustop = "1.0"
tokio = { version = "0.2", features = ["rt-core", "rt-util", "io-driver", "tcp", "udp", "time"]}



[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1
