[package]
name = "rust-doh-nut"
version = "0.1.0"
authors = ["Aron Tsang <arontsang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.21"
futures = "0.3.1"
futures-timer = "2.0.2"
tokio = { version = "0.2", features = ["macros", "rt-core", "rt-util", "sync", "udp"]}

[dependencies.async-std]
version = "1.0.0"
default-features = false
features = ["std"]